Repository TreinaDev/events-app, pull requests merged in 2025-02, with the labels that each got.

#89 Disponibilizar todas as agendas via API (Palestrantes)
  app/controllers/api/v1/speakers_controller.rb
  config/routes.rb
  db/seeds.rb
  spec/requests/api/v1/speaker_api_request_spec.rb
Labels: enhancement

#91 Ajustes nas views, adiciona imagens padrão e ajusta testes
  app/assets/images/bar_code.svg
  app/assets/images/no_banner.png
  app/assets/images/no_logo.png
  app/assets/stylesheets/application.tailwind.css
  app/controllers/schedules_controller.rb
  app/views/dashboard/index.html.erb
  app/views/events/show.html.erb
  app/views/schedules/edit.html.erb
  app/views/schedules/show.html.erb
  app/views/ticket_batches/index.html.erb
  config/locales/models/event.pt-br.yml
  config/locales/pt-br.yml
  config/routes.rb
  spec/system/events/user_creates_event_spec.rb
  spec/system/events/user_deletes_event_spec.rb
  spec/system/events/user_edit_event_spec.rb
  spec/system/schedule_items/user_can_add_a_new_schedule_item_spec.rb
  spec/system/schedules/user_can_view_event_schedule_spec.rb
  spec/system/ticket_batches/user_create_batches_spec.rb
Labels: enhancement

#103 Adicionados os locais para eventos ao projeto
  app/controllers/event_places_controller.rb
  app/models/event_place.rb
  app/models/user.rb
  app/views/event_places/_form.html.erb
  app/views/event_places/edit.html.erb
  app/views/event_places/index.html.erb
  app/views/event_places/new.html.erb
  app/views/event_places/show.html.erb
  app/views/shared/_navbar.html.erb
  config/locales/models/event_place.pt-BR.yml
  config/routes.rb
  db/migrate/20250203203000_create_event_places.rb
  db/schema.rb
  spec/factories/event_places.rb
  spec/models/event_place_spec.rb
  spec/system/event_places/user_can_edit_event_place_spec.rb
  spec/system/event_places/user_can_show_event_place_details_spec.rb
  spec/system/event_places/user_create_event_places_spec.rb
  spec/system/event_places/user_delete_event_place_spec.rb
  spec/system/event_places/user_see_event_places_spec.rb
Labels: enhancement

#107 Adiciona campos ao endpoint events
  app/controllers/api/v1/speakers_controller.rb
  spec/requests/api/v1/speaker_api_request_spec.rb
Labels: enhancement

#112 Adiciona endpoint para palestrantes
  app/controllers/api/v1/speakers_controller.rb
  app/models/schedule_item.rb
  config/routes.rb
  db/migrate/20250203203225_add_code_to_schedule_items.rb
  db/schema.rb
  spec/requests/api/v1/speaker_api_request_spec.rb
Labels: enhancement

#109 Usuário cria requisição para ser verificado
  app/assets/images/checked.svg
  app/assets/images/chevron.svg
  app/assets/images/unchecked.svg
  app/controllers/verifications_controller.rb
  app/javascript/controllers/user_options_controller.js
  app/models/user.rb
  app/models/user_address.rb
  app/models/verification.rb
  app/views/shared/_navbar.html.erb
  app/views/verifications/new.html.erb
  config/locales/models/user.pt-BR.yml
  config/locales/models/user_address.pt-BR.yml
  config/routes.rb
  db/migrate/20250204001409_create_user_addresses.rb
  db/migrate/20250204003728_add_verification_fields_to_user.rb
  db/migrate/20250204051551_create_verifications.rb
  db/migrate/20250204053127_change_user_verification_status_to_integer.rb
  db/schema.rb
  spec/factories/user_addresses.rb
  spec/factories/verifications.rb
  spec/models/user_address_spec.rb
  spec/models/user_spec.rb
  spec/models/verification_spec.rb
  spec/requests/verification/user_create_verification_request_spec.rb
  spec/support/images/id_photo.png
  spec/support/images/residency_proof.jpeg
  spec/system/event_manager_verification/user_creates_a_verification_request_spec.rb
Labels: enhancement

#105 Administrador consegue ver histórico de eventos e editar qualquer evento
  app/assets/stylesheets/application.tailwind.css
  app/controllers/application_controller.rb
  app/controllers/event_places_controller.rb
  app/controllers/events_controller.rb
  app/controllers/schedules_controller.rb
  app/controllers/ticket_batches_controller.rb
  app/views/events/history.html.erb
  app/views/events/show.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
  spec/requests/events/user_create_event_request_spec.rb
  spec/requests/ticket_batches/user_create_ticket_batches_request_spec.rb
  spec/system/events/admin_view_event_history_spec.rb
  spec/system/events/user_deletes_event_spec.rb
Labels: enhancement

#114 Excluir Item de Agenda de Evento
  app/controllers/events_controller.rb
  app/controllers/schedule_items_controller.rb
  app/controllers/verifications_controller.rb
  app/models/event.rb
  app/models/schedule_item.rb
  app/views/dashboard/index.html.erb
  app/views/schedules/show.html.erb
  config/routes.rb
  db/migrate/20250205024835_add_discarded_at_to_schedule_items.rb
  db/schema.rb
  spec/requests/schedule_items/user_delete_schedule_item_request_spec.rb
  spec/system/schedule_items/user_can_delete_a_schedule_item_spec.rb
Labels: enhancement

#108 Usuário consegue editar os lotes
  app/assets/images/bar_code.svg
  app/assets/images/edit.svg
  app/assets/stylesheets/application.tailwind.css
  app/controllers/ticket_batches_controller.rb
  app/views/ticket_batches/_form.html.erb
  app/views/ticket_batches/edit.html.erb
  app/views/ticket_batches/index.html.erb
  app/views/ticket_batches/new.html.erb
  config/routes.rb
  spec/requests/ticket_batches/user_create_ticket_batches_request_spec.rb
  spec/requests/ticket_batches/user_edit_ticket_batches_request_spec.rb
  spec/requests/ticket_batches/user_view_ticket_batches_request_spec.rb
  spec/system/ticket_batches/user_create_batches_spec.rb
  spec/system/ticket_batches/user_edit_batches_spec.rb
  spec/system/ticket_batches/user_view_batches_spec.rb
Labels: enhancement

#119 Novos campos no endpoint events#show
  app/controllers/api/v1/events_controller.rb
  app/controllers/api/v1/speakers_controller.rb
  app/controllers/verifications_controller.rb
  spec/requests/api/v1/event_api_request_spec.rb
Labels: enhancement

#116 Usuário consegue ver e criar comunicados
  app/controllers/announcements_controller.rb
  app/controllers/application_controller.rb
  app/controllers/events_controller.rb
  app/controllers/verifications_controller.rb
  app/models/announcement.rb
  app/models/event.rb
  app/views/announcements/index.html.erb
  app/views/events/show.html.erb
  config/locales/models/announcement.pt-BR.yml
  config/locales/views/announcement.pt-BR.yml
  config/routes.rb
  db/migrate/20250204223854_create_announcements.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/announcements.rb
  spec/models/announcement_spec.rb
  spec/requests/announcement/user_create_announcement_request_spec.rb
  spec/system/announcement/user_create_annoucement_spec.rb
  spec/system/announcement/user_view_announcement_spec.rb
Labels: enhancement

#118 Listar verificações de usuário
  app/controllers/verifications_controller.rb
  app/models/user.rb
  app/views/shared/_navbar.html.erb
  app/views/verifications/index.html.erb
  config/locales/models/verification.pt-BR.yml
  config/routes.rb
  db/seeds.rb
  spec/factories/users.rb
  spec/support/images/address_proof.jpeg
  spec/system/event_manager_verification/user_creates_a_verification_request_spec.rb
  spec/system/event_manager_verification/user_views_verification_requests_spec.rb
Labels: enhancement

#121 Adiciona endpoints de comunicados
  app/controllers/api/v1/Announcements_controller.rb
  app/models/announcement.rb
  config/routes.rb
  db/migrate/20250205212037_add_code_to_announces.rb
  db/schema.rb
  spec/models/announcement_spec.rb
  spec/requests/api/v1/announce_api_request_spec.rb
Labels: enhancement

#130 Aprovar/Reprovar Verificações de Usuário
  app/assets/stylesheets/application.tailwind.css
  app/controllers/verifications_controller.rb
  app/javascript/controllers/verification_controller.js
  app/models/verification.rb
  app/views/verifications/index.html.erb
  app/views/verifications/show.html.erb
  config/locales/models/verification.pt-BR.yml
  config/routes.rb
  spec/requests/verification/user_review_verification_request_spec.rb
  spec/system/verifications/user_view_verification_details_spec.rb
Labels: enhancement

#135 Usuário edita o seu perfil
  app/assets/images/default_avatar.jpg
  app/controllers/profiles_controller.rb
  app/models/user.rb
  app/views/events/history.html.erb
  app/views/profiles/edit.html.erb
  app/views/profiles/show.html.erb
  app/views/shared/_navbar.html.erb
  config/locales/views/profile.pt-BR.yml
  config/routes.rb
  spec/requests/profiles/user_edit_profile_request_spec.rb
  spec/system/authentication/user_edit_profile_spec.rb
Labels: enhancement

#131 Usuário consegue visualizar feedbacks de eventos
  Gemfile
  Gemfile.lock
  app/assets/images/star-outline.svg
  app/assets/images/star.svg
  app/controllers/feedbacks_controller.rb
  app/models/Feedback.rb
  app/models/event.rb
  app/services/participants_api_service.rb
  app/views/events/show.html.erb
  app/views/feedbacks/index.html.erb
  bin/dev
  config/routes.rb
  spec/models/event_spec.rb
  spec/rails_helper.rb
  spec/requests/feedbacks/user_see_feedback_request_spec.rb
  spec/system/feedbacks/user_view_feedbacks_spec.rb
Labels: enhancement

#134 Adicionado o código e as datas do evento na api de items da agenda
  app/controllers/api/v1/speakers_controller.rb
  app/models/schedule_item.rb
  spec/requests/api/v1/speaker_api_request_spec.rb
Labels: bug, enhancement

#142 Endpoint Events ganha novo campo
  app/controllers/api/v1/events_controller.rb
  spec/requests/api/v1/event_api_request_spec.rb
Labels: enhancement

#137 Faz melhorias no seeds e alguma correções e melhorias
  README.md
  app/controllers/announcements_controller.rb
  app/controllers/schedules_controller.rb
  app/views/announcements/index.html.erb
  app/views/events/_form.html.erb
  app/views/events/show.html.erb
  app/views/schedules/show.html.erb
  db/seeds.rb
  doc/API_README.md
  spec/factories/announcements.rb
  spec/factories/events.rb
  spec/models/announcement_spec.rb
  spec/requests/api/v1/event_api_request_spec.rb
  spec/requests/events/user_publish_event_request_spec.rb
  spec/support/images/banner.jpg
  spec/support/images/banner_aws.jpg
  spec/support/images/logo.png
  spec/support/images/logo_aws.png
  spec/support/images/no_banner.png
  spec/support/images/no_logo.png
  spec/system/announcement/user_view_announcement_spec.rb
  spec/system/authentication/user_edit_profile_spec.rb
  spec/system/events/user_creates_event_spec.rb
  spec/system/schedules/user_can_view_event_schedule_spec.rb
Labels: documentation, enhancement

#149 Dashboard de Organizador de Evento
  app/controllers/dashboard_controller.rb
  app/views/dashboard/index.html.erb
  spec/system/dashboard/event_manager_views_dashboard_spec.rb
Labels: enhancement

#151 Dashboard de Admin
  app/assets/stylesheets/application.tailwind.css
  app/controllers/dashboard_controller.rb
  app/views/dashboard/_admin.html.erb
  app/views/dashboard/_event_manager.html.erb
  app/views/dashboard/index.html.erb
  app/views/shared/_navbar.html.erb
  db/seeds.rb
  spec/system/dashboard/event_manager_views_dashboard_spec.rb
  spec/system/dashboard/user_views_dashboard_spec.rb
Labels: enhancement

#147 Melhora a página de feedbacks
  Gemfile
  Gemfile.lock
  README.md
  app/assets/images/star-secondary.svg
  app/assets/stylesheets/application.tailwind.css
  app/controllers/feedbacks_controller.rb
  app/models/Feedback.rb
  app/views/feedbacks/_rating_stars.html.erb
  app/views/feedbacks/index.html.erb
  config/initializers/timeout.rb
  spec/system/breadcrumbs/user_views_feedbacks_breadcrumbs_spec.rb
  spec/system/feedbacks/user_view_feedbacks_spec.rb
Labels: enhancement

#158 Melhorias na pagina de login e cadastro de usuário
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  spec/system/authentication/user_sign_in_spec.rb
Labels: enhancement
