Repository TreinaDev/events-app, pull requests merged in 2025-01, with the labels that each got.

#36 Fix: Form de eventos não mostrava mensagem de erro
  app/views/events/new.html.erb
Labels: bug

#41 Usuário cria Palavras-chave
  app/controllers/keywords_controller.rb
  app/models/keyword.rb
  app/views/categories/index.html.erb
  app/views/keywords/new.html.erb
  config/locales/models/keyword.pt-BR.yml
  config/locales/views/keyword.pt-BR.yml
  config/routes.rb
  db/migrate/20250121194015_create_keywords.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/keywords.rb
  spec/models/keyword_spec.rb
  spec/requests/keywords/user_create_keyword_request_spec.rb
  spec/system/keywords/user_create_keyword_spec.rb
Labels: enhancement

#39 Usuário pode deletar evento
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.tailwind.css
  app/controllers/events_controller.rb
  app/models/event.rb
  app/views/events/index.html.erb
  config/routes.rb
  db/migrate/20250121192226_add_discarded_at_to_events.rb
  db/schema.rb
  spec/requests/events/event_delete_event_request_spec.rb
  spec/system/events/user_deletes_event_spec.rb
Labels: enhancement

#43 API: Exibir apenas eventos marcados como publicado
  app/controllers/api/v1/api_controller.rb
  app/controllers/api/v1/events_controller.rb
  config/routes.rb
  spec/requests/api/event_api_spec.rb
Labels: enhancement

#46 Usuário admin associa palavras-chave a categorias
  app/controllers/categories_controller.rb
  app/models/category.rb
  app/models/category_keyword.rb
  app/models/keyword.rb
  app/views/categories/index.html.erb
  app/views/categories/show.html.erb
  app/views/keywords/new.html.erb
  config/locales/models/keyword.pt-BR.yml
  config/locales/views/category.pt-BR.yml
  config/routes.rb
  db/migrate/20250122194304_create_category_keywords.rb
  db/schema.rb
  db/seeds.rb
  spec/requests/authentication/user_visits_dashboard_request_spec.rb
  spec/requests/keywords/user_associate_keyword_request_spec.rb
  spec/system/categories/user_create_categories_spec.rb
  spec/system/keywords/user_associate_keyword_spec.rb
Labels: enhancement

#48 Usuário edita evento
  app/controllers/events_controller.rb
  app/views/events/_form.html.erb
  app/views/events/edit.html.erb
  app/views/events/new.html.erb
  app/views/events/show.html.erb
  config/routes.rb
  spec/requests/events/user_delete_event_request_spec.rb
  spec/requests/events/user_edit_event_request_spec.rb
  spec/system/events/user_edit_event_spec.rb
Labels: enhancement

#50 Melhorias na página de detalhes de um evento
  app/assets/stylesheets/application.tailwind.css
  app/views/events/show.html.erb
  db/seeds.rb
  spec/support/images/banner.png
  spec/support/images/logo.jpg
  spec/system/events/user_view_event_spec.rb
Labels: enhancement

#53 Adiciona a versão inicial do README.md
  README.md
Labels: documentation

#56 Usuário cria lotes de ingresso
  app/controllers/application_controller.rb
  app/controllers/ticket_batches_controller.rb
  app/models/event.rb
  app/models/ticket_batch.rb
  app/views/events/show.html.erb
  app/views/ticket_batches/index.html.erb
  app/views/ticket_batches/new.html.erb
  config/locales/models/ticket_batch.pt-BR.yml
  config/locales/views/ticket_batch.pt-BR.yml
  config/routes.rb
  db/migrate/20250123200057_create_ticket_batches.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/ticket_batches.rb
  spec/models/ticket_batch_spec.rb
  spec/requests/ticket_batches/user_create_ticket_batches_request_spec.rb
  spec/system/ticket_batches/user_create_batches_spec.rb
Labels: enhancement

#54 Adiciona formulário para criação de itens da agenda
  app/controllers/schedule_items_controller.rb
  app/javascript/controllers/schedule_item_controller.js
  app/models/schedule.rb
  app/models/schedule_item.rb
  app/views/schedule_items/new.html.erb
  app/views/schedules/show.html.erb
  config/locales/models/schedule_items.pt-BR.yml
  config/routes.rb
  db/migrate/20250124205708_create_schedule_items.rb
  db/schema.rb
  spec/factories/schedule_items.rb
  spec/factories/schedules.rb
  spec/models/schedule_item_spec.rb
  spec/requests/schedule_items/user_create_schedule_item_request_spec.rb
  spec/system/schedule_items/user_can_add_a_new_schedule_item_spec.rb
Labels: enhancement

#60 Otimiza o tempo de execução dos testes
  spec/rails_helper.rb
  spec/system/authentication/user_sign_up_spec.rb
  spec/system/categories/user_create_categories_spec.rb
  spec/system/events/user_creates_event_spec.rb
  spec/system/events/user_deletes_event_spec.rb
  spec/system/keywords/user_create_keyword_spec.rb
  spec/system/schedule_items/user_can_add_a_new_schedule_item_spec.rb
  spec/system/ticket_batches/user_create_batches_spec.rb
Labels: enhancement

#65 Disponibiliza endpoint para detalhes de eventos
  app/controllers/api/v1/events_controller.rb
  app/models/event.rb
  config/routes.rb
  db/migrate/20250127212754_add_uuid_to_events.rb
  db/schema.rb
  spec/models/event_spec.rb
  spec/requests/api/event_api_request_spec.rb
Labels: enhancement

#66 Disponibiliza endpoint para fornecer identificador único do palestrante
  app/controllers/api/v1/api_controller.rb
  app/controllers/api/v1/speakers_controller.rb
  app/models/schedule_item.rb
  app/models/speaker.rb
  config/routes.rb
  db/migrate/20250128184745_create_speakers.rb
  db/schema.rb
  spec/models/speaker_spec.rb
  spec/requests/api/v1/event_api_request_spec.rb
  spec/requests/api/v1/speaker_api_request_spec.rb
Labels: enhancement

#55 Adiciona detalhes das atividades na página show da agenda
  app/controllers/schedules_controller.rb
  app/javascript/controllers/schedule_controller.js
  app/views/schedules/show.html.erb
  config/application.rb
  spec/models/ticket_batch_spec.rb
  spec/system/schedules/user_can_view_event_schedule_details_spec.rb
Labels: enhancement

#72 Adicionados endpoints para lista de lotes de ingressos e detalhes de um lote
  app/controllers/api/v1/ticket_batches_controller.rb
  config/routes.rb
  spec/requests/api/v1/ticket_batch_api_request_spec.rb
Labels: enhancement

#71 Refatora a relação entre Eventos e Agendas
  app/controllers/api/v1/events_controller.rb
  app/models/event.rb
  app/models/schedule.rb
  app/models/schedule_item.rb
  app/models/ticket_batch.rb
  app/views/events/show.html.erb
  app/views/schedules/show.html.erb
  config/locales/pt-br.yml
  db/migrate/20250128203306_change_fields_of_schedules.rb
  db/schema.rb
  spec/factories/schedules.rb
  spec/models/event_spec.rb
  spec/models/schedule_item_spec.rb
  spec/models/schedule_spec.rb
  spec/models/ticket_batch_spec.rb
  spec/requests/api/v1/event_api_request_spec.rb
  spec/requests/schedule/user_create_schedule_request_spec.rb
  spec/requests/schedule/user_edit_schedule_request_spec.rb
  spec/system/events/user_creates_event_spec.rb
  spec/system/schedule_items/user_can_add_a_new_schedule_item_spec.rb
  spec/system/schedules/user_can_define_event_schedule_spec.rb
  spec/system/schedules/user_can_edit_event_schedule_spec.rb
  spec/system/schedules/user_can_view_event_schedule_details_spec.rb
Labels: enhancement

#75 Disponibiliza eventos no qual o palestrante está cadastrado
  app/controllers/api/v1/speakers_controller.rb
  app/models/schedule_item.rb
  app/models/speaker.rb
  config/routes.rb
  db/migrate/20250130193151_add_unique_index_to_speakers.rb
  db/schema.rb
  db/seeds.rb
  spec/models/speaker_spec.rb
  spec/requests/api/v1/speaker_api_request_spec.rb
Labels: enhancement

#78 Melhora os detalhes dos retornos da rota de eventos da API de palestrantes
  app/controllers/api/v1/speakers_controller.rb
  spec/requests/api/v1/speaker_api_request_spec.rb
Labels: bug

#84 style: adjusts forms css to adhere to a standard and adds html title …
  app/assets/images/wind.svg
  app/assets/stylesheets/application.tailwind.css
  app/views/categories/index.html.erb
  app/views/categories/new.html.erb
  app/views/categories/show.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/events/_form.html.erb
  app/views/events/edit.html.erb
  app/views/events/new.html.erb
  app/views/keywords/new.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/dashboard.html.erb
  app/views/schedule_items/new.html.erb
  app/views/ticket_batches/new.html.erb
  config/tailwind.config.js
  spec/system/categories/user_create_categories_spec.rb
  spec/system/categories/user_view_categories_spec.rb
Labels: enhancement
